version: "3.8"

services:

  signup-db:
    image: signup-db:04-07
    build:
      dockerfile: docker/04-07-persistent-databases/signup-db/Dockerfile
    volumes:
      - type: bind
        source: C:\databases
        target: C:\data