Vagrant.configure("2") do |config|
  
  config.vm.define "manager" do |manager|
    manager.vm.box = "bento/ubuntu-20.04" 
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", type: "dhcp"
    manager.vm.provision "shell", path: "setup.sh"
    manager.vm.provision "shell", path: "pull-images.sh"
    manager.vm.synced_folder "../..", "/docker4dotnet"
    manager.vm.provider :hyperv do |v|
      v.vmname = "manager"
      v.maxmemory = 2000
      v.cpus = 2
    end
    manager.vm.provider :virtualbox do |v|
      v.name = "manager"
      v.memory = 2000
      v.cpus = 2
    end
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "bento/ubuntu-20.04" 
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.provision "shell", path: "setup.sh"
    worker.vm.provision "shell", path: "pull-images.sh"
    worker.vm.provider :hyperv do |v|
      v.vmname = "worker"
      v.maxmemory = 1500
      v.cpus = 1
    end
    worker.vm.provider :virtualbox do |v|
      v.name = "worker"
      v.memory = 1500
      v.cpus = 1
    end
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "bento/ubuntu-20.04" 
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", type: "dhcp"
    worker2.vm.provision "shell", path: "setup.sh"
    worker2.vm.provision "shell", path: "pull-images.sh"
    worker2.vm.provider :hyperv do |v|
      v.vmname = "worker2"
      v.maxmemory = 1500
      v.cpus = 1
    end
    worker2.vm.provider :virtualbox do |v|
      v.name = "worker2"
      v.memory = 1500
      v.cpus = 1
    end
  end

  config.vm.define "winworker" do |winworker|
    winworker.vm.box = "kiamol/windows-2019"
    winworker.vm.hostname = "winworker"
    winworker.vm.network "private_network", type: "dhcp"
    winworker.vm.guest = "windows"    
    winworker.vm.communicator = "winrm"
    winworker.vm.provision "shell", path: "setup.ps1", powershell_elevated_interactive: true, reboot: true 
    winworker.vm.provision "shell", path: "pull-images.ps1", powershell_elevated_interactive: true
    winworker.vm.provider :hyperv do |v|
      v.vmname = "winworker"
      v.maxmemory = 4000
      v.cpus = 2
    end    
    winworker.vm.provider :virtualbox do |v|
      v.name = "winworker"
      v.memory = 4000
      v.cpus = 2
    end
  end
  
end